#!/bin/bash

info_user()
{
local AMSURE
if [ -n "$1" ] ; then
        read -n 1 -p "$1 (y/[a]): " AMSURE
else
        read -n 1 AMSURE
fi
echo "" 1>&2
case "$AMSURE" in
        y|Y|yes) cat /etc/passwd | awk -F':' '{print $1 " " $3 " " $6}'
                ;;
        n|N|no) echo "Exit"
                exit 1
                ;;
        *) echo "Nothing to be done"
                ;;
esac
}

info_user "Are you sure you want to see login, UID and Path (y/[a]): "

# Write a script which displays only the login, UID and Path of each entry
# of the /etc/passwd file.

# https://habr.com/ru/post/158971/

# 1 - Users 3 - UID 6 - PATH

